### ISSUE TITLE
Wrap models not machines?

### ISSUE THREAD

**Issue by ablaom** [pat-alt/ConformalPrediction.jl#5]
@pat-alt 

Congratualations on the launch of this new package 🎉  Great to have the integration with MLJ!

I'm not familiar with conformal prediction, but I nevertheless wonder why this package wraps MLJ *machines* rather than models. If you wrap models, then you will buy into MLJ's model composition. So, a "conformally wrapped model" will behave like any other model: you can insert in pipeline, can wrap in tuning strategy, and so forth. 

New models in MLJ generally implement the ["basement level" *model* API](https://alan-turing-institute.github.io/MLJ.jl/dev/adding_models_for_general_use/). Machines are a higher level abstraction for: (i) user interaction; and (ii) syntax for building [learning networks](https://alan-turing-institute.github.io/MLJ.jl/dev/composing_models/#Learning-Networks) which are ultimately "exported" as standalone model types. 

Here are other examples of model wrapping in MLJ: [`EnsembleModel`](https://github.com/JuliaAI/MLJEnsembles.jl) ([docs](https://alan-turing-institute.github.io/MLJ.jl/dev/homogeneous_ensembles/#Homogeneous-Ensembles)), `BinaryThresholdPredictor`, `TunedModel`, `IteratedModel`. What makes things a little complicated is the model hierarchy: the model supertype for the wrapped model depends on the supertype of the atomic model. So for example, we don't just have `EnsembleModel` we have `DeterministicEnsembleModel` (for ordinary point predictors) and `ProbabilisticEnsembleModel` (for probabilistic predictors) but the user only sees a single constructor `EnsembleModel`; see [here](https://github.com/JuliaAI/MLJEnsembles.jl/blob/8a31400cceae74d565f1cdad55afc1b6523784d4/src/ensembles.jl#L204). (A longer term goal is to drop the hierarchy in favour of pure trait interface, which will simplify things, but that's a little ways off yet.) 

Happy to provide further guidance. 

cc @azev77

**Comment by azev77** [comment]
@ablaom currently MLJ models can give deterministic & probabilistic predictions (GLM predicts an entire distribution). 
If methods for conformal predictive inference become more developed, can users automatically combine their favorite (appropriate) deterministic predictor w/ their favorite predictive interval method, to make probabilistic predictions? 

For example: 
currently ` model = LGBMRegressor()` gives deterministic predictions 
would a user be able to create a new model composing a deterministic model `LGBMRegressor` w/ their favorite (appropriate) predictive interval method e.g. `conformal(type=naive)` to create a new model w/ probabilistic predictions?

**Comment by ablaom** [comment]
> For example:
currently model = LGBMRegressor() gives deterministic predictions
would a user be able to create a new model composing a deterministic model LGBMRegressor w/ their favorite (appropriate) predictive interval method e.g. conformal(type=naive) to create a new model w/ probabilistic predictions?

Yes, I guess that's the design I am suggesting. So, similar to the way `BinaryThresholdPredictor` wraps a probabilistic predictor and makes it deterministic.

**Comment by pat-alt** [comment]
Hi @ablaom 👋🏽  Thanks very much for this suggestion and sorry for the delayed response (been battling Covid this week while also trying to finish my JuliaCon proceedings submission 😅 ). I will implement this first thing once I turn back to working on this package some time next week 👍🏽

**Comment by pat-alt** [comment]
Implemented in #10, but will keep this open for now, because I still want to iron out a few things (some related questions [here](https://github.com/pat-alt/ConformalPrediction.jl/commit/05f27f2152f43dc2ac994e71a0ea21782ef3dd55#commitcomment-86569932)).

**Comment by pat-alt** [comment]
#18 should now be strictly in line with MLJ @ablaom, so I will close this. Will still need to figure out how to handle downstream tasks like `evaluate` in the future.
